Add a space for event collections in the labeler input.
world-federation-of-advertisers/virtual-people-common pull request #58
Opened 2023-03-28 20:55 UTC by jonmolle

These can be data provider campaign ids, some meta identifier, etc. Intended to identify a specific set of events that the model provider knows for model building.

Specifically requested as a way to map consented campaign ids to events in panel exchange, but if there's a better spot for this I'm happy to move it.

2023-03-28 20:55 UTC, wfa-reviewable commented
<!-- Reviewable:start -->
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)
<!-- Reviewable:end -->

2023-03-28 21:08 UTC, wliue requested changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NRe1fEH9tb1-la_d15p:-NRe1fEH9tb1-la_d15q:b-qsphh) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5618121285b07080f289f22cd412e6eac93a8871/src/main/proto/wfa/virtual_people/common/event.proto#L132)):*
> ```protobuf
>   // Unique event collection identifier. Used to map back to specific consented
>   // event groupings defined by the Data Provider. Unlike event_id, these are
>   // intended to be used for labeling.
> ```

How will these be used for labeling? It doesn't sound right that labeler behavior is affected by event groupings.



_Code quote:_
```protobuf
  // event groupings defined by the Data Provider. Unlike event_id, these are
  // intended to be used for labeling.
```


<!-- Sent from Reviewable.io -->

2023-03-28 21:26 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NRe1fEH9tb1-la_d15p:-NRe5MiI2uDdKZqFUax7:b-7ua4ex) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5618121285b07080f289f22cd412e6eac93a8871/src/main/proto/wfa/virtual_people/common/event.proto#L132)):*
<details><summary><i>Previously, wliue (Wei Liu) wrote…</i></summary><blockquote>

How will these be used for labeling? It doesn't sound right that labeler behavior is affected by event groupings.
</blockquote></details>

There has been a request to be able to filter events down to ones from specific collections (campaigns, in this case) when training a model (from the panel exchange results). I should probably reword this, but this seems like the most logical place to put that information (unless you think EventId is a better place for this. It is unique compared to EventId.id, as a note).


<!-- Sent from Reviewable.io -->

2023-03-29 15:15 UTC, kungfucraig reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NRe1fEH9tb1-la_d15p:-NRhvsUo7Kj0P8PyPBqk:bo3y6h6) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5618121285b07080f289f22cd412e6eac93a8871/src/main/proto/wfa/virtual_people/common/event.proto#L132)):*
<details><summary><i>Previously, jonmolle wrote…</i></summary><blockquote>

There has been a request to be able to filter events down to ones from specific collections (campaigns, in this case) when training a model (from the panel exchange results). I should probably reword this, but this seems like the most logical place to put that information (unless you think EventId is a better place for this. It is unique compared to EventId.id, as a note).
</blockquote></details>

Is the idea just to pass this through or to use it as part of generating the label?


<!-- Sent from Reviewable.io -->

2023-04-03 15:01 UTC, stevenwarejones reviewed
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: all files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @wliue)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NRe1fEH9tb1-la_d15p:-NS6c_7hCJzVBFbR_Ux5:b-lgu7sa) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5618121285b07080f289f22cd412e6eac93a8871/src/main/proto/wfa/virtual_people/common/event.proto#L132)):*
<details><summary><i>Previously, kungfucraig (Craig Wright) wrote…</i></summary><blockquote>

Is the idea just to pass this through or to use it as part of generating the label?
</blockquote></details>

I believe the use case is for better VID model training based


<!-- Sent from Reviewable.io -->

2023-04-10 17:39 UTC, jonmolle reviewed
Updated this based on external discussions, please take a look. Attempted to avoid using subprotos, but otherwise matches the one-pager.

> Dismissed @wliue from a discussion.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-:-NSgEq7n9Bs1JTwVDqK5:b-pysi13)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 132 at r1](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NRe1fEH9tb1-la_d15p:-NSgEe7wEQ9jLRMvyXNf:b-9j00li) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/5618121285b07080f289f22cd412e6eac93a8871/src/main/proto/wfa/virtual_people/common/event.proto#L132)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

I believe the use case is for better VID model training based
</blockquote></details>

I propose closing this based on external conversation and refactoring.


<!-- Sent from Reviewable.io -->

2023-04-13 23:28 UTC, wliue approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @duliomatos1 and @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-17 14:43 UTC, stevenwarejones requested changes
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @jonmolle)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NTEejNb-1ADGXoJbRy4:-NTEejNc1upbx9mPe1rE:b-49on4o) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f5c9dc4a44deddd5338fc5c10849a1c7195e1c67/src/main/proto/wfa/virtual_people/common/event.proto#L72)):*
> ```protobuf
> // Represents information about the parent event that is not used in labeling or
> // measurement. These are not intended to be unique across all EDPs.
> message TrafficInfo {
> ```

`TrainingInfo` maybe? if its not going to be used for labeling


<!-- Sent from Reviewable.io -->

2023-04-17 15:17 UTC, jonmolle reviewed
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @duliomatos1 and @stevenwarejones)

___
*[`src/main/proto/wfa/virtual_people/common/event.proto` line 72 at r2](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-NTEejNb-1ADGXoJbRy4:-NTElFs84UNW4I8_ZYPq:betd866) ([raw file](https://github.com/world-federation-of-advertisers/virtual-people-common/blob/f5c9dc4a44deddd5338fc5c10849a1c7195e1c67/src/main/proto/wfa/virtual_people/common/event.proto#L72)):*
<details><summary><i>Previously, stevenwarejones (Steven Ware Jones) wrote…</i></summary><blockquote>

`TrainingInfo` maybe? if its not going to be used for labeling
</blockquote></details>

The idea I have is that I don't know that all use cases will forever be training; only that this is "not labeling". I think the comments are very clear, but this is coming from my bias knowing that it is easier to add things to a proto than it is to remove/change mistakes. If you have strong feelings, though, I'm happy to change it, both are accurate descriptions here.


<!-- Sent from Reviewable.io -->

2023-04-18 15:45 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2023-04-18 15:45 UTC, stevenwarejones approved these changes
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @duliomatos1)



<!-- Sent from Reviewable.io -->

2023-04-18 15:59 UTC, jonmolle reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58#-:-NTK4yaw0E_1bq3vKr2i:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @stevenwarejones)



<!-- Sent from Reviewable.io -->

2023-04-18 17:46 UTC, stevenwarejones approved these changes
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/world-federation-of-advertisers/virtual-people-common/58)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @jonmolle)



<!-- Sent from Reviewable.io -->

2023-04-18 20:34 UTC, merged